### ISSUE TITLE
Barcodeapi gives HTTP/503 during startup 

### ISSUE THREAD

**Issue by ualex73** [turiphro/barcode-shopping-list#3]
I tried the following command:
`docker build -t barcodeapi src/api && docker run -it --rm -v $PWD/src/api:/app -p7000:5000 -v $PWD/lists/:/app/lists barcodeapi`

This gives a HTTP/503 error, as shown below:

[2022-07-31 10:07:58 +0000] [7] [INFO] Starting gunicorn 20.0.4
[2022-07-31 10:07:58 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
[2022-07-31 10:07:58 +0000] [7] [INFO] Using worker: threads
[2022-07-31 10:07:58 +0000] [10] [INFO] Booting worker with pid: 10
[2022-07-31 10:07:58 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/run.py", line 1, in <module>
    from api_svc import create_api
  File "/app/api_svc.py", line 20, in <module>
    RESOLVERS = [CommandResolver(), PlaintextResolver(), AlbertHeijnResolver(),
  File "/app/resolvers/albert_heijn.py", line 14, in __init__
    self.__reconnect__()
  File "/app/resolvers/albert_heijn.py", line 17, in __reconnect__
    self.connector = AHConnector()
  File "/usr/local/lib/python3.7/site-packages/supermarktconnector/ah.py", line 22, in __init__
    self._access_token = self.get_anonymous_access_token()
  File "/usr/local/lib/python3.7/site-packages/supermarktconnector/ah.py", line 18, in get_anonymous_access_token
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://ms.ah.nl/create-anonymous-member-token?client=appie-anonymous
[2022-07-31 10:07:58 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-07-31 10:07:58 +0000] [7] [INFO] Shutting down: Master
[2022-07-31 10:07:58 +0000] [7] [INFO] Reason: Worker failed to boot.`

**Comment by turiphro** [comment]
Thanks for filing this issue.

It looks like the latest `supermarktconnector` release only made it to Python 3.8+. I've bumped the base images to 3.8 with  #138ce2aac42a4e203e4a9fa3e92b311b1bb11ea1

The following works again:

```bash
# terminal 1:
docker build --no-cache -t barcodeapi src/api/ && docker run -it --rm -v $PWD/src/api:/app -p7000:5000 -v $PWD/lists/:/app/lists barcodeapi

# terminal 2:
docker build -t barcodecli --no-cache src/cli && docker run -it --rm --net host -v $PWD/src/cli:/app barcodecli --hostname localhost --port 7000
```

**Comment by ualex73** [comment]
Thanks it works now 👍
